### ISSUE TITLE
Missing image in the documents section

### ISSUE THREAD

**Issue by s1-en** [indentlabs/notebook#889] opened 2021-03-04 15:43 UTC
### Expected behavior
There should be an image in there.

### Actual behavior
There is none.

### Steps to reproduce the behavior
1. Go to https://www.notebook.ai/documents
2. See the missing image.

![image](https://user-images.githubusercontent.com/63731521/109989200-3e833880-7d43-11eb-809e-e1e92beace24.png)

**Comment by drusepth** [comment] 2021-03-16 23:37
Hey @s1-en, are you still seeing this problem? I've been unable to reproduce it. If you are, do you have any console errors (specifically, 404s on images that failed to load)? Thanks!

**Comment by s1-en** [comment] 2021-03-16 23:47
Going to https://www.notebook.ai/images/documents/analysis.jpeg (the linked image) leads to a 404 page

![image](https://user-images.githubusercontent.com/63731521/111394110-fd9d0380-86f4-11eb-8fa6-e8a2e677c8bf.png)

**Comment by drusepth** [comment] 2021-03-17 22:27
Super interesting bug, thanks for reporting. Looks like https://github.com/rails/sprockets-rails/issues/304 bit us good. A fix for this should go live with the above commit in the next production release. Thanks again! :+1:

**Closed** 2021-03-17 22:27 UTC

**Comment by s1-en** [comment] 2021-03-17 23:50
Glad to help!
